apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kotlin-oxford-dictionaries
  annotations:
    github.com/project-slug: sparkmuse/kotlin-oxford-dictionaries
spec:
  type: other
  lifecycle: unknown
  owner: team-a
